python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
python $PWD/bot.py
